# Generated by Django 4.2.4 on 2024-12-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_products', '0002_remove_subcategory_subcategory_category_and_more'),
        ('product_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_product_lists', to='backend_products.product', verbose_name='Selected Product'),
        ),
    ]
